services: 
  db: 
    image: mongo:latest
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports: 
      - "27017:27017"
    volumes:
      - ./data/db:/data/db